modLoader = "javafml"
# The loader version doesn't matter. Modify the NeoForge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
license = "MIT"
issueTrackerURL = "https://github.com/Creators-of-Create/Ponder/issues"

[[mods]]
modId = "ponder"
version = "1.0.82+mc1.21.1"
displayName = "Ponder"
displayURL = "https://github.com/Creators-of-Create/Ponder"
logoFile = "logo.png"
authors = "simibubi, Pepper, zelophed"
credits = "Special Thanks to IThundxr, Jozufozu, Snownee, gamez7, tterrag and Grimmauld"
description = '''Visual in-Game Documentation'''

[[mixins]]
config="ponder.mixins.json"

[[mixins]]
config="ponder-common.mixins.json"

[[dependencies."ponder"]]
modId = "neoforge"
type="required"
versionRange = "[21.1.206,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."ponder"]]
modId = "minecraft"
type="required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies."ponder"]]
modId = "flywheel"
type="required"
versionRange = "[1.0.0,2.0)"
ordering = "AFTER"
side = "CLIENT"
